import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="primary">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button className="btn btn-secondary rounded-full">daisyUI Button</button>
      <button className="btn btn-primary rounded-full">daisyUI Button</button>

      <footer className="primary">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by MS-hack
        </a>
      </footer>
    </div>
  )
}

export default Home
