import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { EthereumAuthProvider, SelfID } from '@self.id/web'

const Home: NextPage = () => {
  useEffect(async () => {
    const addresses = await window.ethereum.enable()
    // "local" | "mainnet-gateway" | "testnet-clay" | "testnet-clay-gateway"
    // https://developers.ceramic.network/learn/networks/
    const self = await SelfID.authenticate({
      authProvider: new EthereumAuthProvider(window.ethereum, addresses[0]),
      ceramic: 'testnet-clay',
      connectNetwork: 'testnet-clay',
    })
    console.log('self', self)
    //await self.set('basicProfile', { name: 'Ming-der Wang' })
    const ming = await self.get('basicProfile')
    console.log(ming)
  }, [])

  return (
    <div className="primary">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button className="btn btn-secondary rounded-full">connect</button>

      <footer className="primary">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by MS-hack
        </a>
      </footer>
    </div>
  )
}

export default Home
